---

# This docker-compose file is required to bind ports in development,
# since binding ports in regular compose file will ruin scaling
# in production. Due to how `ports` directive is merged with two files.
#
# This file is ignored in production, but
# it is automatically picked up in development with:
#
#  $ docker-compose up

version: "3.8"
services:

  db:
    ports:
      - "5432:5432"

  web:
    environment:
      - JSON_SERVER_HOST=json-server
      - JSON_SERVER_PORT=3000
    ports:
      # We only bind ports directly in development:
      - "8000:8000"
    volumes:
      # We only mount source code in development:
      - .:/code
    build:
      # Needed for fixing permissions of files created by Docker
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    links:
      - json-server

  json-server:
    build:
      context: ./docker/json-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - webnet
    volumes:
      - ./json-server:/data
    command: -H 0.0.0.0 -p 3000

networks:
  # Fake API network:
  bitrixnet:
